Sys 287 jest it up (#39)
This needs manual testing prior to merging to main which is when it will be considered done. I'll manually update the ticket when that's complete
* SYS-287 add jest-it-up to store code coverage

* change coverage step so that failing the build is dependent on the switch

* change coverage step so that failing the build is dependent on the switch

* change coverage step so that failing the build is dependent on the switch

* only check coverage if unit tests were successfull and coverage is available

* remove duplicated test run and add opts to test coverage script

* prettier fix

---------

Co-authored-by: Chris Freels <cafreels@gmail.com>

diff --git a/.github/workflows/reusable-node-ci.yml b/.github/workflows/reusable-node-ci.yml
--- a/.github/workflows/reusable-node-ci.yml
+++ b/.github/workflows/reusable-node-ci.yml
@@ -28,6 +28,10 @@ on:
         required: false
         type: boolean
         default: ${{ vars.IS_UNIT_TESTS_REQUIRED == 'true' }}
+      target-coverage:
+        required: false
+        type: string
+        default: ${{ vars.TARGET_COVERAGE }}
 env:
   NODE_VERSION: ${{ inputs.node-version }}
   RUST_VERSION: ${{ inputs.rust-version }}
@@ -141,12 +145,18 @@ jobs:
           fi
         continue-on-error: true
 
-      - name: Run Unit Tests
-        id: unit_tests
+      - name: Run Tests and Collect Coverage
         run: |
-          echo "Running Unit Tests..."
-          npm test
-          echo "Unit Tests complete."
+          if npm run | grep -q "test:coverage"; then
+            OUTPUT=$(npm run test:coverage")
+            echo "$OUTPUT"
+            COVERAGE=$(echo "$OUTPUT" | grep -oP '(?<=All files)[^\d]*\K\d+')
+            npm run posttest
+          else
+            echo "test:coverage not found, running `npm run test`"
+            npm run test
+            COVERAGE=0
+          fi
         continue-on-error: true
 
       - name: Check if any step failed
@@ -195,3 +205,36 @@ jobs:
             echo "Linting, Format Check, Unit Tests and Apply Patches are required to pass by default but may be overridden at the Org or Repo level by setting the corresponding variable(s) to 'true' or 'false'. Please notify Systems & Automation to make this request"
             exit 1
           fi
+
+      - name: Check Coverage
+        if: steps.unit_tests.outcome == 'success' && steps.test-and-coverage.outputs.has-coverage == 'true'
+        run: |
+          THRESHOLD=$(grep -oP '(?<=lines: )\d+' jest.config.js)
+          TARGET_COVERAGE=${{ inputs.target-coverage }}
+
+          if [ "$COVERAGE" -ge "$TARGET_COVERAGE" ]; then
+            echo "Coverage is above or equal to the target of $TARGET_COVERAGE%. Test passes."
+          elif [ "$COVERAGE" -ge "$THRESHOLD" ]; then
+            echo "Coverage is below $TARGET_COVERAGE% but meets or exceeds the current threshold. Test passes."
+          elif [ "$COVERAGE" -eq 0 ]; then
+            echo "Coverage check skipped as test:coverage was not found."
+          else
+            echo "Coverage is below $TARGET_COVERAGE% and below the current threshold."
+            if [ "$IS_UNIT_TESTS_REQUIRED" = "true" ]; then
+              echo "Coverage has decreased below the threshold and tests are required to pass. Failing the build."
+              exit 1
+            else
+              echo "Coverage has decreased below the threshold but tests are NOT required to pass."
+            fi
+          fi
+
+      - name: Commit Jest-it-up changes (if applicable)
+        if: steps.test-and-coverage.outputs.has-coverage == 'true'
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add jest.config.js
+          git commit -m "chore: update coverage thresholds with jest-it-up" || echo "No changes to commit"
+
+      - name: Push changes
+        run: git push || echo "No changes to push"
